apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deliver.triggered
      requests:
        - "curl --header 'Authorization: Bearer {{.env.secret_argo_token}}'
          --request POST --data
          '{\"infos\":[{\"name\":\"triggeredid\",\"value\":\"{{.id}}\"},{\"name\
          \":\"shkeptncontext\",\"value\":\"{{.shkeptncontext}}\"}],\"prune\":t\
          rue}'
          https://{{ $argo_api_fqdn }}/api/v1/applications/{{.da\
          ta.labels.appname}}/sync"
      envFrom:
        - name: secret_argo_token
          secretRef:
            name: argo
            key: token
      subscriptionID: {{ $subscription_id }}
      sendFinished: false
